from .base import *

DEBUG = False
JWT_SIGNING_KEY = require_strong_jwt_signing_key(SECRET_KEY, JWT_SIGNING_KEY, debug=DEBUG)
SIMPLE_JWT["SIGNING_KEY"] = JWT_SIGNING_KEY
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
