# Generated by Django 5.1.15 on 2026-04-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'active'), ('maintenance', 'maintenance'), ('inactive', 'inactive')], default='active', max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hostname', models.CharField(max_length=255)),
                ('internal_ip', models.GenericIPAddressField(protocol='IPv4')),
                ('external_ip', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('os_version', models.CharField(max_length=255)),
                ('cpu_cores', models.PositiveIntegerField()),
                ('memory_gb', models.DecimalField(decimal_places=2, max_digits=8)),
                ('disk_summary', models.TextField(blank=True)),
                ('lifecycle_status', models.CharField(choices=[('online', 'online'), ('offline', 'offline'), ('maintenance', 'maintenance'), ('pre_allocated', 'pre_allocated')], default='online', max_length=32)),
                ('environment', models.CharField(choices=[('dev', 'dev'), ('test', 'test'), ('prod', 'prod')], default='dev', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'manual'), ('agent', 'agent'), ('api', 'api')], default='manual', max_length=32)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servers', to='cmdb.idc')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hostname', 'internal_ip'), name='uniq_server_hostname_internal_ip')],
            },
        ),
    ]
